repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: flake8
        args: [--max-line-length=100, "--ignore=E203,E111,E114,E121,W503"]
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --indent=2]
    -   id: check-yaml
    -   id: sort-simple-yaml
-   repo: https://github.com/desbma/black-2spaces
    rev: e9de72c180edf74d7372609c93179954bdd79f11  # pragma: allowlist secret
    additional_dependencies: ['click@8.0.4']
    hooks:
    -   id: black
        args: [-l 100]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
        language_version: python3
        args: [-w 120, -m 3, -tc, --project=twiser]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
    - id: require-ascii
    - id: script-must-have-extension
    - id: forbid-binary
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
- repo: https://github.com/Yelp/detect-secrets
  rev: v0.12.5
  hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.1
  hooks:
    - id: python-no-eval
    - id: python-check-blanket-noqa
- repo: https://github.com/asottile/yesqa
  rev: v0.0.11
  hooks:
    - id: yesqa
- repo: https://github.com/myint/eradicate
  rev: 522ed7ce2da82d33b3e2331bf50d4671c5a5af9a  # pragma: allowlist secret
  hooks:
    - id: eradicate
      exclude: ^(docs/conf.py)$
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--in-place,--wrap-summaries=100,--wrap-descriptions=100]
